name: Building
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: SCA
        run: npm audit --production 
      - name: bearer SAST
        run: bearer scan juice-shop
      - run: npm run build
      - run: npm test
